version: "3.8"

volumes:
  nothing:

services:
  core:
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    build:
      args:
        - BASE_IMAGE=nvidia/cuda:12.2.0-devel-ubuntu22.04
        - PYTHON_VERSION=3.10
        - UID=${HOST_UID-1001}
        - GID=${HOST_GID-1002}
      context: ./
      dockerfile: ./Dockerfile
    tty: true
    # volumes:
    #     - ../../:/home/challenger/ascender
    #     - nothing:/home/challenger/ascender/.venv/
    ports:
        - 9000:9000